//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trello.Repositorio {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class QueriesCardsRepositorio {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal QueriesCardsRepositorio() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trello.Repositorio.QueriesCardsRepositorio", typeof(QueriesCardsRepositorio).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UPDATE CARD SET Titulo = @Titulo, Conteudo = @Conteudo, Assunto = @Assunto, Etiqueta = @Etiqueta, DataEntrega = @DataEntrega WHERE Id = @Id.
        /// </summary>
        internal static string alterarCard {
            get {
                return ResourceManager.GetString("alterarCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a INSERT INTO CARD (Titulo, Conteudo, Assunto, Etiqueta, DataPublicacao, DataEntrega) values (@Titulo, @Conteudo, @Assunto, @Etiqueta, GETDATE(), @DataEntrega).
        /// </summary>
        internal static string cadastrarCard {
            get {
                return ResourceManager.GetString("cadastrarCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT * FROM CARD ORDER BY DATAPUBLICACAO DESC.
        /// </summary>
        internal static string cardPorId {
            get {
                return ResourceManager.GetString("cardPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DELETE CARD WHERE Id = @Id.
        /// </summary>
        internal static string deletarCard {
            get {
                return ResourceManager.GetString("deletarCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT * FROM CARD WHERE TITULO LIKE &apos;%&apos; PALAVRA &apos;%&apos; OR CONTEUDO LIKE &apos;%&apos; PALAVRA &apos;%&apos;.
        /// </summary>
        internal static string obterCardPorPalavraChave {
            get {
                return ResourceManager.GetString("obterCardPorPalavraChave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT * FROM CARD.
        /// </summary>
        internal static string obterCards {
            get {
                return ResourceManager.GetString("obterCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT * FROM CARD WHERE Titulo Like &apos;%&apos; + @titulo + &apos;%&apos;.
        /// </summary>
        internal static string obterCardsPorTitulo {
            get {
                return ResourceManager.GetString("obterCardsPorTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT * FROM CARDCOMENTARIO.
        /// </summary>
        internal static string obterComentarios {
            get {
                return ResourceManager.GetString("obterComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT * FROM CARDCOMENTARIO WHERE IDCARD = @idCard.
        /// </summary>
        internal static string obterComentariosPorId {
            get {
                return ResourceManager.GetString("obterComentariosPorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT TOP 3 * FROM CARD ORDER BY DESC.
        /// </summary>
        internal static string topCards {
            get {
                return ResourceManager.GetString("topCards", resourceCulture);
            }
        }
    }
}
